const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES',
      ADD_TO_BASKET = 'ADD_TO_BASKET',
      REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET',
      REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES',
      SET_PAGE = 'SET_PAGE'

export {
    ADD_TO_FAVOURITES,
    ADD_TO_BASKET,
    REMOVE_FROM_BASKET,
    REMOVE_FROM_FAVOURITES,
    SET_PAGE
}