const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES',
      ADD_TO_BASKET = 'ADD_TO_BASKET',
      REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET',
      REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES',
      SET_PAGE = 'SET_PAGE',
      FETCH_BEERS_INIT = 'FETCH_BEERS_INIT',
      FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS',
      FETCH_BEERS_FAILURE = 'FETCH_BEERS_FAILURE'

export {
    ADD_TO_FAVOURITES,
    ADD_TO_BASKET,
    REMOVE_FROM_BASKET,
    REMOVE_FROM_FAVOURITES,
    SET_PAGE,
    FETCH_BEERS_FAILURE,
    FETCH_BEERS_SUCCESS,
    FETCH_BEERS_INIT
}